#!/usr/bin/env python
import os
import sys
import django
import random

# Add the backend directory to the Python path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Setup Django
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
django.setup()

from accounts.models import User
from topics.models import Topic
from vocabulary.models import Vocabulary


def create_sample_data():
    print("Creating sample data...")

    # Create admin user
    admin_user, created = User.objects.get_or_create(
        email="admin@wordify.com",
        defaults={
            "username": "admin",
            "first_name": "Admin",
            "last_name": "Manager",
            "role": "admin",
            "is_staff": True,
            "is_superuser": True,
        },
    )
    if created:
        admin_user.set_password("admin123")
        admin_user.save()
        print("✓ Admin user created")

    # Create regular users
    users_data = [
        {
            "email": "john@example.com",
            "username": "john_doe",
            "first_name": "John",
            "last_name": "Doe",
            "password": "user123",
        },
        {
            "email": "jane@example.com",
            "username": "jane_smith",
            "first_name": "Jane",
            "last_name": "Smith",
            "password": "jane123",
        },
        {
            "email": "mike@example.com",
            "username": "mike_johnson",
            "first_name": "Mike",
            "last_name": "Johnson",
            "password": "mike123",
        },
    ]

    created_users = []
    for user_data in users_data:
        user, created = User.objects.get_or_create(
            email=user_data["email"],
            defaults={
                "username": user_data["username"],
                "first_name": user_data["first_name"],
                "last_name": user_data["last_name"],
                "role": "user",
            },
        )
        if created:
            user.set_password(user_data["password"])
            user.save()
            created_users.append(user)
            print(f"✓ User {user.email} created")

    # Create 10 topics
    topics_data = [
        {
            "name": "Animals & Wildlife",
            "description": "Learn vocabulary about animals, pets, and wildlife from around the world",
            "color": "#10B981",
        },
        {
            "name": "Food & Cooking",
            "description": "Vocabulary related to food, cooking, restaurants, and culinary arts",
            "color": "#F59E0B",
        },
        {
            "name": "Technology & Innovation",
            "description": "Modern technology, gadgets, software, and digital innovation terms",
            "color": "#3B82F6",
        },
        {
            "name": "Business & Finance",
            "description": "Terms related to business operations, finance, economics, and management",
            "color": "#6366F1",
        },
        {
            "name": "Arts & Culture",
            "description": "Vocabulary about visual arts, music, literature, and cultural expressions",
            "color": "#EC4899",
        },
        {
            "name": "Travel & Geography",
            "description": "Words related to travel, countries, landmarks, and geographical features",
            "color": "#14B8A6",
        },
        {
            "name": "Health & Medicine",
            "description": "Medical terminology, health conditions, wellness, and healthcare systems",
            "color": "#EF4444",
        },
        {
            "name": "Science & Nature",
            "description": "Scientific concepts, natural phenomena, and environmental terms",
            "color": "#22C55E",
        },
        {
            "name": "Sports & Recreation",
            "description": "Vocabulary related to sports, games, outdoor activities, and hobbies",
            "color": "#F97316",
        },
        {
            "name": "Education & Academia",
            "description": "Terms related to learning, teaching, academic disciplines, and educational systems",
            "color": "#8B5CF6",
        },
    ]

    created_topics = []
    for topic_data in topics_data:
        topic, created = Topic.objects.get_or_create(
            name=topic_data["name"], defaults=topic_data
        )
        created_topics.append(topic)
        if created:
            print(f"✓ Topic '{topic.name}' created")

    # Create vocabulary for each topic (20 words per topic)
    vocabulary_data = {
        "Animals & Wildlife": [
            {
                "word": "Elephant",
                "pronunciation": "/ˈɛlɪfənt/",
                "meaning": "A very large mammal with a trunk, large ears, and tusks",
                "example": "The elephant is the largest land animal in the world.",
                "difficulty": "easy",
            },
            {
                "word": "Butterfly",
                "pronunciation": "/ˈbʌtərflaɪ/",
                "meaning": "A flying insect with large colorful wings",
                "example": "The butterfly landed gently on the flower.",
                "difficulty": "easy",
            },
            {
                "word": "Rhinoceros",
                "pronunciation": "/raɪˈnɒsərəs/",
                "meaning": "A large thick-skinned mammal with one or two horns on the nose",
                "example": "The rhinoceros is an endangered species in many parts of Africa.",
                "difficulty": "hard",
            },
            {
                "word": "Giraffe",
                "pronunciation": "/dʒɪˈrɑːf/",
                "meaning": "A large African mammal with a very long neck and legs",
                "example": "The giraffe used its long neck to reach leaves high in the tree.",
                "difficulty": "easy",
            },
            {
                "word": "Penguin",
                "pronunciation": "/ˈpɛŋɡwɪn/",
                "meaning": "A flightless bird that lives in cold regions, especially Antarctica",
                "example": "Penguins are excellent swimmers and can dive deep into the ocean.",
                "difficulty": "easy",
            },
            {
                "word": "Cheetah",
                "pronunciation": "/ˈtʃiːtə/",
                "meaning": "A large wild cat with a slender body known for being the fastest land animal",
                "example": "The cheetah can run at speeds of up to 70 mph.",
                "difficulty": "medium",
            },
            {
                "word": "Orangutan",
                "pronunciation": "/əˈræŋuːtæn/",
                "meaning": "A large ape with reddish-brown hair native to Indonesia and Malaysia",
                "example": "Orangutans spend most of their time in trees.",
                "difficulty": "hard",
            },
            {
                "word": "Platypus",
                "pronunciation": "/ˈplætɪpəs/",
                "meaning": "An Australian mammal that lays eggs and has a duck-like bill",
                "example": "The platypus is one of the few venomous mammals.",
                "difficulty": "hard",
            },
            {
                "word": "Chameleon",
                "pronunciation": "/kəˈmiːliən/",
                "meaning": "A lizard that can change color to match its surroundings",
                "example": "The chameleon changed its color to blend in with the leaves.",
                "difficulty": "medium",
            },
            {
                "word": "Dolphin",
                "pronunciation": "/ˈdɒlfɪn/",
                "meaning": "A marine mammal known for its intelligence and playful behavior",
                "example": "Dolphins communicate with each other using clicks and whistles.",
                "difficulty": "easy",
            },
            {
                "word": "Koala",
                "pronunciation": "/koʊˈɑːlə/",
                "meaning": "An Australian marsupial that feeds on eucalyptus leaves",
                "example": "The koala sleeps for up to 20 hours a day.",
                "difficulty": "easy",
            },
            {
                "word": "Scorpion",
                "pronunciation": "/ˈskɔːrpiən/",
                "meaning": "An arachnid with a poisonous sting at the end of its tail",
                "example": "The scorpion uses its pincers to catch prey.",
                "difficulty": "medium",
            },
            {
                "word": "Narwhal",
                "pronunciation": "/ˈnɑːrwəl/",
                "meaning": "An Arctic whale with a long spiral tusk",
                "example": "The narwhal's tusk is actually an elongated tooth.",
                "difficulty": "hard",
            },
            {
                "word": "Pangolin",
                "pronunciation": "/ˈpæŋɡəlɪn/",
                "meaning": "A scaly anteater native to Asia and Africa",
                "example": "The pangolin is the most trafficked mammal in the world.",
                "difficulty": "hard",
            },
            {
                "word": "Flamingo",
                "pronunciation": "/fləˈmɪŋɡoʊ/",
                "meaning": "A tall wading bird with pink feathers and a curved bill",
                "example": "Flamingos often stand on one leg while resting.",
                "difficulty": "medium",
            },
            {
                "word": "Octopus",
                "pronunciation": "/ˈɒktəpəs/",
                "meaning": "A sea creature with eight arms and a soft body",
                "example": "The octopus can change both its color and texture to hide from predators.",
                "difficulty": "medium",
            },
            {
                "word": "Sloth",
                "pronunciation": "/sloʊθ/",
                "meaning": "A slow-moving mammal that hangs upside down from trees",
                "example": "The sloth moves so slowly that algae grows on its fur.",
                "difficulty": "easy",
            },
            {
                "word": "Wolverine",
                "pronunciation": "/ˈwʊlvəriːn/",
                "meaning": "A small but fierce carnivorous mammal related to weasels",
                "example": "Despite its small size, the wolverine is known for its strength and ferocity.",
                "difficulty": "hard",
            },
            {
                "word": "Axolotl",
                "pronunciation": "/ˈæksəlɒtl/",
                "meaning": "A Mexican salamander that retains its larval features throughout its life",
                "example": "The axolotl can regenerate lost limbs and other body parts.",
                "difficulty": "hard",
            },
            {
                "word": "Mongoose",
                "pronunciation": "/ˈmɒŋɡuːs/",
                "meaning": "A small carnivorous mammal known for its ability to kill snakes",
                "example": "The mongoose is immune to some snake venoms.",
                "difficulty": "medium",
            },
        ],
        "Food & Cooking": [
            {
                "word": "Cuisine",
                "pronunciation": "/kwɪˈziːn/",
                "meaning": "A style or method of cooking, especially as characteristic of a particular country",
                "example": "Italian cuisine is famous for its pasta and pizza dishes.",
                "difficulty": "medium",
            },
            {
                "word": "Appetizer",
                "pronunciation": "/ˈæpɪtaɪzər/",
                "meaning": "A small dish of food served before the main course",
                "example": "We ordered bruschetta as an appetizer before our main meal.",
                "difficulty": "medium",
            },
            {
                "word": "Marinade",
                "pronunciation": "/ˈmærɪneɪd/",
                "meaning": "A sauce in which meat, fish, or other food is soaked before cooking",
                "example": "The chef prepared a garlic and herb marinade for the chicken.",
                "difficulty": "medium",
            },
            {
                "word": "Sauté",
                "pronunciation": "/soʊˈteɪ/",
                "meaning": "To fry quickly in a little hot fat",
                "example": "Sauté the onions until they become translucent.",
                "difficulty": "hard",
            },
            {
                "word": "Garnish",
                "pronunciation": "/ˈɡɑːrnɪʃ/",
                "meaning": "A decoration or embellishment added to a dish",
                "example": "The chef added a parsley garnish to the plate.",
                "difficulty": "medium",
            },
            {
                "word": "Culinary",
                "pronunciation": "/ˈkʌlɪneri/",
                "meaning": "Relating to cooking or kitchens",
                "example": "She studied culinary arts at a prestigious cooking school.",
                "difficulty": "medium",
            },
            {
                "word": "Simmer",
                "pronunciation": "/ˈsɪmər/",
                "meaning": "To cook just below boiling point",
                "example": "Let the soup simmer for 30 minutes to develop the flavors.",
                "difficulty": "easy",
            },
            {
                "word": "Blanch",
                "pronunciation": "/blɑːntʃ/",
                "meaning": "To scald vegetables briefly and then plunge them into cold water",
                "example": "Blanch the asparagus before grilling it.",
                "difficulty": "hard",
            },
            {
                "word": "Knead",
                "pronunciation": "/niːd/",
                "meaning": "To work dough by pressing and folding it",
                "example": "Knead the bread dough until it becomes elastic.",
                "difficulty": "easy",
            },
            {
                "word": "Broil",
                "pronunciation": "/brɔɪl/",
                "meaning": "To cook by direct heat, especially under a grill",
                "example": "Broil the fish for about 5 minutes on each side.",
                "difficulty": "medium",
            },
            {
                "word": "Julienne",
                "pronunciation": "/ˌʒuːliˈɛn/",
                "meaning": "To cut food into thin strips",
                "example": "Julienne the carrots for the salad.",
                "difficulty": "hard",
            },
            {
                "word": "Caramelize",
                "pronunciation": "/ˈkærəməlaɪz/",
                "meaning": "To heat sugar until it turns brown and develops a characteristic flavor",
                "example": "Caramelize the onions for a sweet, rich flavor.",
                "difficulty": "medium",
            },
            {
                "word": "Poach",
                "pronunciation": "/poʊtʃ/",
                "meaning": "To cook food by simmering it in liquid",
                "example": "Poach the eggs for exactly three minutes.",
                "difficulty": "medium",
            },
            {
                "word": "Zest",
                "pronunciation": "/zɛst/",
                "meaning": "The outer colored part of citrus fruit skin used for flavoring",
                "example": "Add some lemon zest to the cake batter.",
                "difficulty": "easy",
            },
            {
                "word": "Braise",
                "pronunciation": "/breɪz/",
                "meaning": "To cook food slowly in a small amount of liquid in a covered pot",
                "example": "Braise the short ribs until they are tender.",
                "difficulty": "hard",
            },
            {
                "word": "Infuse",
                "pronunciation": "/ɪnˈfjuːz/",
                "meaning": "To extract flavors by soaking ingredients in liquid",
                "example": "Infuse the oil with garlic and herbs.",
                "difficulty": "medium",
            },
            {
                "word": "Deglaze",
                "pronunciation": "/diːˈɡleɪz/",
                "meaning": "To add liquid to a hot pan to loosen browned bits of food",
                "example": "Deglaze the pan with wine to make a sauce.",
                "difficulty": "hard",
            },
            {
                "word": "Mince",
                "pronunciation": "/mɪns/",
                "meaning": "To cut food into very small pieces",
                "example": "Mince the garlic finely before adding it to the oil.",
                "difficulty": "easy",
            },
            {
                "word": "Reduction",
                "pronunciation": "/rɪˈdʌkʃən/",
                "meaning": "A concentrated sauce made by boiling to reduce the volume",
                "example": "The chef made a balsamic reduction to drizzle over the dish.",
                "difficulty": "medium",
            },
            {
                "word": "Emulsion",
                "pronunciation": "/ɪˈmʌlʃən/",
                "meaning": "A mixture of two liquids that don't normally mix, like oil and water",
                "example": "Mayonnaise is an emulsion of oil, egg yolks, and vinegar.",
                "difficulty": "hard",
            },
        ],
        "Technology & Innovation": [
            {
                "word": "Algorithm",
                "pronunciation": "/ˈælɡərɪðəm/",
                "meaning": "A set of rules or instructions for solving a problem",
                "example": "The search algorithm helps users find relevant information quickly.",
                "difficulty": "hard",
            },
            {
                "word": "Software",
                "pronunciation": "/ˈsɔːftwɛər/",
                "meaning": "Computer programs and applications",
                "example": "The company develops software for mobile applications.",
                "difficulty": "medium",
            },
            {
                "word": "Blockchain",
                "pronunciation": "/ˈblɒktʃeɪn/",
                "meaning": "A digital ledger in which transactions are recorded chronologically and publicly",
                "example": "Blockchain technology is used in cryptocurrencies like Bitcoin.",
                "difficulty": "hard",
            },
            {
                "word": "Bandwidth",
                "pronunciation": "/ˈbændwɪdθ/",
                "meaning": "The maximum rate of data transfer across a network",
                "example": "Streaming high-definition videos requires significant bandwidth.",
                "difficulty": "medium",
            },
            {
                "word": "Encryption",
                "pronunciation": "/ɪnˈkrɪpʃən/",
                "meaning": "The process of converting information into a code to prevent unauthorized access",
                "example": "End-to-end encryption ensures that only the sender and recipient can read messages.",
                "difficulty": "hard",
            },
            {
                "word": "Interface",
                "pronunciation": "/ˈɪntərfeɪs/",
                "meaning": "A point where two systems meet and interact",
                "example": "The user interface was designed to be intuitive and easy to navigate.",
                "difficulty": "medium",
            },
            {
                "word": "Cloud Computing",
                "pronunciation": "/klaʊd kəmˈpjuːtɪŋ/",
                "meaning": "The delivery of computing services over the internet",
                "example": "Many businesses are moving their operations to cloud computing platforms.",
                "difficulty": "medium",
            },
            {
                "word": "Artificial Intelligence",
                "pronunciation": "/ˌɑːrtɪˈfɪʃəl ɪnˈtɛlɪdʒəns/",
                "meaning": "The simulation of human intelligence in machines",
                "example": "Artificial intelligence is used in voice assistants like Siri and Alexa.",
                "difficulty": "hard",
            },
            {
                "word": "Cybersecurity",
                "pronunciation": "/ˈsaɪbərˌsɪkjʊərɪti/",
                "meaning": "The practice of protecting systems and networks from digital attacks",
                "example": "Companies invest heavily in cybersecurity to protect sensitive data.",
                "difficulty": "medium",
            },
            {
                "word": "Virtual Reality",
                "pronunciation": "/ˈvɜːrtʃuəl riˈælɪti/",
                "meaning": "A computer-generated simulation of a three-dimensional environment",
                "example": "Virtual reality headsets provide an immersive gaming experience.",
                "difficulty": "medium",
            },
            {
                "word": "Biometrics",
                "pronunciation": "/ˌbaɪoʊˈmɛtrɪks/",
                "meaning": "The measurement and analysis of unique physical or behavioral characteristics",
                "example": "Fingerprint scanners use biometrics to verify identity.",
                "difficulty": "hard",
            },
            {
                "word": "Nanotechnology",
                "pronunciation": "/ˌnænoʊtɛkˈnɒlədʒi/",
                "meaning": "The manipulation of matter on an atomic and molecular scale",
                "example": "Nanotechnology is being used to develop more efficient solar panels.",
                "difficulty": "hard",
            },
            {
                "word": "Augmented Reality",
                "pronunciation": "/ɔːɡˈmɛntɪd riˈælɪti/",
                "meaning": "Technology that superimposes computer-generated images on a user's view of the real world",
                "example": "Pokemon Go uses augmented reality to place virtual creatures in real-world locations.",
                "difficulty": "hard",
            },
            {
                "word": "Firmware",
                "pronunciation": "/ˈfɜːrmwɛər/",
                "meaning": "Permanent software programmed into a read-only memory",
                "example": "The manufacturer released a firmware update to fix bugs in the device.",
                "difficulty": "medium",
            },
            {
                "word": "Quantum Computing",
                "pronunciation": "/ˈkwɒntəm kəmˈpjuːtɪŋ/",
                "meaning": "Computing using quantum-mechanical phenomena",
                "example": "Quantum computing has the potential to solve complex problems much faster than traditional computers.",
                "difficulty": "hard",
            },
            {
                "word": "Scalability",
                "pronunciation": "/ˌskeɪləˈbɪlɪti/",
                "meaning": "The capability of a system to handle a growing amount of work",
                "example": "The startup designed their infrastructure with scalability in mind.",
                "difficulty": "medium",
            },
            {
                "word": "Internet of Things",
                "pronunciation": "/ˈɪntərnɛt ʌv θɪŋz/",
                "meaning": "The interconnection of everyday devices via the internet",
                "example": "Smart home systems are part of the Internet of Things ecosystem.",
                "difficulty": "medium",
            },
            {
                "word": "Machine Learning",
                "pronunciation": "/məˈʃiːn ˈlɜːrnɪŋ/",
                "meaning": "A type of artificial intelligence that allows computers to learn without being explicitly programmed",
                "example": "Netflix uses machine learning to recommend shows based on your viewing history.",
                "difficulty": "hard",
            },
            {
                "word": "Cryptocurrency",
                "pronunciation": "/ˈkrɪptoʊˌkʌrənsi/",
                "meaning": "A digital currency that uses cryptography for security",
                "example": "Bitcoin was the first widely adopted cryptocurrency.",
                "difficulty": "medium",
            },
            {
                "word": "Robotics",
                "pronunciation": "/roʊˈbɒtɪks/",
                "meaning": "The branch of technology that deals with the design and operation of robots",
                "example": "Robotics is revolutionizing manufacturing and healthcare industries.",
                "difficulty": "medium",
            },
        ],
        "Business & Finance": [
            {
                "word": "Equity",
                "pronunciation": "/ˈɛkwɪti/",
                "meaning": "The value of shares issued by a company",
                "example": "The startup raised $2 million in equity financing.",
                "difficulty": "medium",
            },
            {
                "word": "Diversification",
                "pronunciation": "/daɪˌvɜːrsɪfɪˈkeɪʃən/",
                "meaning": "The practice of varying investments to reduce risk",
                "example": "Diversification is a key strategy for managing investment risk.",
                "difficulty": "hard",
            },
            {
                "word": "Liquidity",
                "pronunciation": "/lɪˈkwɪdɪti/",
                "meaning": "The ease with which an asset can be converted into cash",
                "example": "The company faced a liquidity crisis and couldn't pay its short-term debts.",
                "difficulty": "hard",
            },
            {
                "word": "Depreciation",
                "pronunciation": "/dɪˌpriːʃiˈeɪʃən/",
                "meaning": "A decrease in the value of an asset over time",
                "example": "The company calculated the depreciation of its equipment for tax purposes.",
                "difficulty": "medium",
            },
            {
                "word": "Merger",
                "pronunciation": "/ˈmɜːrdʒər/",
                "meaning": "The combination of two companies to form a new entity",
                "example": "The merger between the two tech giants created the largest company in the industry.",
                "difficulty": "easy",
            },
            {
                "word": "Dividend",
                "pronunciation": "/ˈdɪvɪdɛnd/",
                "meaning": "A sum of money paid regularly by a company to its shareholders",
                "example": "The company announced a quarterly dividend of 50 cents per share.",
                "difficulty": "medium",
            },
            {
                "word": "Inflation",
                "pronunciation": "/ɪnˈfleɪʃən/",
                "meaning": "A general increase in prices and fall in the purchasing value of money",
                "example": "The central bank raised interest rates to combat inflation.",
                "difficulty": "medium",
            },
            {
                "word": "Collateral",
                "pronunciation": "/kəˈlætərəl/",
                "meaning": "Property or assets offered to secure a loan",
                "example": "The borrower used his house as collateral for the business loan.",
                "difficulty": "medium",
            },
            {
                "word": "Leverage",
                "pronunciation": "/ˈlɛvərɪdʒ/",
                "meaning": "The use of borrowed capital to increase potential return",
                "example": "The company used leverage to finance its expansion.",
                "difficulty": "hard",
            },
            {
                "word": "Arbitrage",
                "pronunciation": "/ˈɑːrbɪtrɑːʒ/",
                "meaning": "The simultaneous buying and selling of assets to profit from price differences",
                "example": "Traders use arbitrage to exploit price differences in different markets.",
                "difficulty": "hard",
            },
            {
                "word": "Amortization",
                "pronunciation": "/əˌmɔːrtɪˈzeɪʃən/",
                "meaning": "The gradual reduction of a debt by regular payments",
                "example": "The mortgage amortization schedule shows how much of each payment goes toward principal and interest.",
                "difficulty": "hard",
            },
            {
                "word": "Fiscal",
                "pronunciation": "/ˈfɪskəl/",
                "meaning": "Relating to government revenue, especially taxes",
                "example": "The government implemented new fiscal policies to stimulate economic growth.",
                "difficulty": "medium",
            },
            {
                "word": "Liability",
                "pronunciation": "/ˌlaɪəˈbɪlɪti/",
                "meaning": "A company's financial debt or obligations",
                "example": "The company's liabilities exceeded its assets, indicating financial trouble.",
                "difficulty": "medium",
            },
            {
                "word": "Portfolio",
                "pronunciation": "/pɔːrtˈfoʊlioʊ/",
                "meaning": "A collection of investments held by a person or organization",
                "example": "A balanced investment portfolio typically includes stocks, bonds, and cash.",
                "difficulty": "medium",
            },
            {
                "word": "Recession",
                "pronunciation": "/rɪˈsɛʃən/",
                "meaning": "A period of temporary economic decline",
                "example": "During the recession, many businesses had to lay off employees.",
                "difficulty": "medium",
            },
            {
                "word": "Venture Capital",
                "pronunciation": "/ˈvɛntʃər ˈkæpɪtl/",
                "meaning": "Capital invested in a project with substantial risk",
                "example": "The startup secured venture capital funding to develop its new product.",
                "difficulty": "medium",
            },
            {
                "word": "Hedge Fund",
                "pronunciation": "/hɛdʒ fʌnd/",
                "meaning": "A limited partnership of investors that uses high-risk methods to obtain large profits",
                "example": "Hedge funds are typically only available to accredited investors.",
                "difficulty": "hard",
            },
            {
                "word": "Solvency",
                "pronunciation": "/ˈsɒlvənsi/",
                "meaning": "The ability of a company to meet its long-term financial obligations",
                "example": "The audit confirmed the company's solvency despite recent market challenges.",
                "difficulty": "hard",
            },
            {
                "word": "Commodity",
                "pronunciation": "/kəˈmɒdɪti/",
                "meaning": "A raw material or primary agricultural product that can be bought and sold",
                "example": "Gold and oil are examples of widely traded commodities.",
                "difficulty": "medium",
            },
            {
                "word": "Benchmark",
                "pronunciation": "/ˈbɛntʃmɑːrk/",
                "meaning": "A standard against which performance can be measured",
                "example": "The S&P 500 is often used as a benchmark for U.S. stock market performance.",
                "difficulty": "medium",
            },
        ],
        "Arts & Culture": [
            {
                "word": "Renaissance",
                "pronunciation": "/ˈrɛnəsɑːns/",
                "meaning": "A period of European cultural, artistic, and scientific revival in the 14th-17th centuries",
                "example": "Leonardo da Vinci was a prominent figure during the Renaissance.",
                "difficulty": "medium",
            },
            {
                "word": "Impressionism",
                "pronunciation": "/ɪmˈprɛʃənɪzəm/",
                "meaning": "An art movement characterized by small, visible brushstrokes and emphasis on light",
                "example": "Monet's water lilies are classic examples of Impressionism.",
                "difficulty": "medium",
            },
            {
                "word": "Composition",
                "pronunciation": "/ˌkɒmpəˈzɪʃən/",
                "meaning": "The arrangement of elements in a work of art or music",
                "example": "The composition of the photograph drew attention to the subject's eyes.",
                "difficulty": "medium",
            },
            {
                "word": "Curator",
                "pronunciation": "/kjʊˈreɪtər/",
                "meaning": "A person who manages a collection of artifacts or works of art",
                "example": "The museum curator organized an exhibition of contemporary photography.",
                "difficulty": "medium",
            },
            {
                "word": "Avant-garde",
                "pronunciation": "/ˌævɒnt ˈɡɑːrd/",
                "meaning": "New and experimental ideas and methods in art, music, or literature",
                "example": "The avant-garde film challenged traditional narrative structures.",
                "difficulty": "hard",
            },
            {
                "word": "Baroque",
                "pronunciation": "/bəˈroʊk/",
                "meaning": "A highly ornate and extravagant style of art, music, and architecture",
                "example": "The church features elaborate Baroque architecture.",
                "difficulty": "medium",
            },
            {
                "word": "Motif",
                "pronunciation": "/moʊˈtiːf/",
                "meaning": "A recurring element that has symbolic significance in a work of art",
                "example": "The butterfly motif appears throughout the artist's work, symbolizing transformation.",
                "difficulty": "hard",
            },
            {
                "word": "Vernacular",
                "pronunciation": "/vərˈnækjələr/",
                "meaning": "The language or dialect spoken by ordinary people in a particular region",
                "example": "The novel was written in the vernacular of rural Mississippi.",
                "difficulty": "hard",
            },
            {
                "word": "Aesthetics",
                "pronunciation": "/ɛsˈθɛtɪks/",
                "meaning": "The branch of philosophy dealing with beauty and taste",
                "example": "The designer focused on the aesthetics of the space rather than just functionality.",
                "difficulty": "hard",
            },
            {
                "word": "Juxtaposition",
                "pronunciation": "/ˌdʒʌkstəpəˈzɪʃən/",
                "meaning": "The act of placing things side by side, especially for comparison or contrast",
                "example": "The artist used juxtaposition of old and new elements in her collage.",
                "difficulty": "hard",
            },
            {
                "word": "Metaphor",
                "pronunciation": "/ˈmɛtəfɔːr/",
                "meaning": "A figure of speech in which a word or phrase is applied to an object or action that it does not literally denote",
                "example": 'The phrase "time is money" is a common metaphor in business.',
                "difficulty": "medium",
            },
            {
                "word": "Satire",
                "pronunciation": "/ˈsætaɪər/",
                "meaning": "The use of humor, irony, exaggeration, or ridicule to expose and criticize people's stupidity or vices",
                "example": "The novel is a satire of modern corporate culture.",
                "difficulty": "medium",
            },
            {
                "word": "Symbolism",
                "pronunciation": "/ˈsɪmbəlɪzəm/",
                "meaning": "The use of symbols to represent ideas or qualities",
                "example": "The dove is often used as symbolism for peace in art and literature.",
                "difficulty": "medium",
            },
            {
                "word": "Protagonist",
                "pronunciation": "/proʊˈtæɡənɪst/",
                "meaning": "The main character in a story, movie, or play",
                "example": "The protagonist overcomes numerous obstacles throughout the novel.",
                "difficulty": "medium",
            },
            {
                "word": "Allegory",
                "pronunciation": "/ˈæləɡɔːri/",
                "meaning": "A story, poem, or picture that can be interpreted to reveal a hidden meaning",
                "example": "Animal Farm is an allegory for the Russian Revolution.",
                "difficulty": "hard",
            },
            {
                "word": "Surrealism",
                "pronunciation": "/səˈriːəlɪzəm/",
                "meaning": "A 20th-century avant-garde movement in art and literature that sought to release the creative potential of the unconscious mind",
                "example": "Salvador Dalí's melting clocks are iconic images of Surrealism.",
                "difficulty": "hard",
            },
            {
                "word": "Sonnet",
                "pronunciation": "/ˈsɒnɪt/",
                "meaning": "A poem of fourteen lines using any of a number of formal rhyme schemes",
                "example": "Shakespeare wrote 154 sonnets during his lifetime.",
                "difficulty": "medium",
            },
            {
                "word": "Monologue",
                "pronunciation": "/ˈmɒnəlɒɡ/",
                "meaning": "A long speech by one actor in a play or movie, or as a theatrical entertainment",
                "example": "The actor delivered a powerful monologue that moved the audience to tears.",
                "difficulty": "medium",
            },
            {
                "word": "Expressionism",
                "pronunciation": "/ɪkˈsprɛʃənɪzəm/",
                "meaning": "A style of painting, music, or drama in which the artist seeks to express emotional experience rather than impressions of the external world",
                "example": "The Scream by Edvard Munch is a famous example of Expressionism.",
                "difficulty": "hard",
            },
            {
                "word": "Anthology",
                "pronunciation": "/ænˈθɒlədʒi/",
                "meaning": "A collection of literary works chosen by the compiler",
                "example": "The anthology includes poems from various cultures and time periods.",
                "difficulty": "medium",
            },
        ],
        "Travel & Geography": [
            {
                "word": "Archipelago",
                "pronunciation": "/ˌɑːrkɪˈpɛləɡoʊ/",
                "meaning": "A group of islands",
                "example": "Japan is an archipelago consisting of four main islands and thousands of smaller ones.",
                "difficulty": "hard",
            },
            {
                "word": "Peninsula",
                "pronunciation": "/pəˈnɪnsjʊlə/",
                "meaning": "A piece of land almost surrounded by water",
                "example": "Florida is a peninsula extending into the Gulf of Mexico.",
                "difficulty": "medium",
            },
            {
                "word": "Itinerary",
                "pronunciation": "/aɪˈtɪnəˌrɛri/",
                "meaning": "A planned route or journey",
                "example": "Our European vacation itinerary includes stops in Paris, Rome, and Barcelona.",
                "difficulty": "medium",
            },
            {
                "word": "Excursion",
                "pronunciation": "/ɪkˈskɜːrʒən/",
                "meaning": "A short journey or trip, especially one taken as a leisure activity",
                "example": "We took a day excursion to visit the nearby ruins.",
                "difficulty": "medium",
            },
            {
                "word": "Terrain",
                "pronunciation": "/təˈreɪn/",
                "meaning": "A stretch of land, especially with regard to its physical features",
                "example": "The rocky terrain made hiking difficult.",
                "difficulty": "medium",
            },
            {
                "word": "Cartography",
                "pronunciation": "/kɑːrˈtɒɡrəfi/",
                "meaning": "The science or practice of drawing maps",
                "example": "Modern cartography relies heavily on satellite imagery.",
                "difficulty": "hard",
            },
            {
                "word": "Fjord",
                "pronunciation": "/fiˈɔːrd/",
                "meaning": "A long, narrow, deep inlet of the sea between high cliffs",
                "example": "Norway is famous for its spectacular fjords.",
                "difficulty": "hard",
            },
            {
                "word": "Plateau",
                "pronunciation": "/plæˈtoʊ/",
                "meaning": "An area of relatively level high ground",
                "example": "The Tibetan Plateau is the highest and largest plateau in the world.",
                "difficulty": "medium",
            },
            {
                "word": "Equator",
                "pronunciation": "/ɪˈkweɪtər/",
                "meaning": "An imaginary line around the middle of the Earth at an equal distance from the North and South Poles",
                "example": "Ecuador is named after the equator, which runs through the country.",
                "difficulty": "easy",
            },
            {
                "word": "Hemisphere",
                "pronunciation": "/ˈhɛmɪsfɪər/",
                "meaning": "Half of the earth, usually divided into northern and southern or eastern and western",
                "example": "Australia is located entirely in the Southern Hemisphere.",
                "difficulty": "medium",
            },
            {
                "word": "Topography",
                "pronunciation": "/təˈpɒɡrəfi/",
                "meaning": "The arrangement of the natural and artificial physical features of an area",
                "example": "The topography of the region includes mountains, valleys, and rivers.",
                "difficulty": "hard",
            },
            {
                "word": "Estuary",
                "pronunciation": "/ˈɛstʃuˌɛri/",
                "meaning": "The tidal mouth of a large river where it meets the sea",
                "example": "The Thames Estuary is an important shipping route into London.",
                "difficulty": "hard",
            },
            {
                "word": "Oasis",
                "pronunciation": "/oʊˈeɪsɪs/",
                "meaning": "A fertile spot in a desert where water is found",
                "example": "The travelers rested at the oasis before continuing their journey across the desert.",
                "difficulty": "medium",
            },
            {
                "word": "Tributary",
                "pronunciation": "/ˈtrɪbjʊˌtɛri/",
                "meaning": "A river or stream flowing into a larger river or lake",
                "example": "The Missouri River is the longest tributary of the Mississippi River.",
                "difficulty": "medium",
            },
            {
                "word": "Isthmus",
                "pronunciation": "/ˈɪsməs/",
                "meaning": "A narrow strip of land connecting two larger land areas",
                "example": "The Isthmus of Panama connects North and South America.",
                "difficulty": "hard",
            },
            {
                "word": "Delta",
                "pronunciation": "/ˈdɛltə/",
                "meaning": "A triangular area of land formed at the mouth of a river",
                "example": "The Nile Delta is one of the world's largest river deltas.",
                "difficulty": "medium",
            },
            {
                "word": "Tundra",
                "pronunciation": "/ˈtʌndrə/",
                "meaning": "A vast, flat, treeless Arctic region",
                "example": "The tundra is characterized by permafrost, which makes it difficult for trees to grow.",
                "difficulty": "medium",
            },
            {
                "word": "Atoll",
                "pronunciation": "/ˈætɒl/",
                "meaning": "A ring-shaped coral reef or island",
                "example": "The Maldives consists of 26 atolls in the Indian Ocean.",
                "difficulty": "hard",
            },
            {
                "word": "Escarpment",
                "pronunciation": "/ɪˈskɑːrpmənt/",
                "meaning": "A long, steep slope at the edge of a plateau or separating areas of land at different heights",
                "example": "The Niagara Escarpment extends from New York State through Ontario, Canada.",
                "difficulty": "hard",
            },
            {
                "word": "Savanna",
                "pronunciation": "/səˈvænə/",
                "meaning": "A grassy plain in tropical and subtropical regions with few trees",
                "example": "The African savanna is home to many large mammals, including lions and elephants.",
                "difficulty": "medium",
            },
        ],
        "Health & Medicine": [
            {
                "word": "Diagnosis",
                "pronunciation": "/ˌdaɪəɡˈnoʊsɪs/",
                "meaning": "The identification of an illness or disorder",
                "example": "The doctor made a diagnosis of pneumonia after examining the patient.",
                "difficulty": "medium",
            },
            {
                "word": "Prognosis",
                "pronunciation": "/prɒɡˈnoʊsɪs/",
                "meaning": "A forecast of the likely outcome of a disease or injury",
                "example": "The patient received a positive prognosis after successful treatment.",
                "difficulty": "hard",
            },
            {
                "word": "Antibiotic",
                "pronunciation": "/ˌæntibaɪˈɒtɪk/",
                "meaning": "A medicine that inhibits the growth of or destroys microorganisms",
                "example": "The doctor prescribed antibiotics to treat the bacterial infection.",
                "difficulty": "medium",
            },
            {
                "word": "Cardiovascular",
                "pronunciation": "/ˌkɑːrdioʊˈvæskjʊlər/",
                "meaning": "Relating to the heart and blood vessels",
                "example": "Regular exercise improves cardiovascular health.",
                "difficulty": "hard",
            },
            {
                "word": "Immunization",
                "pronunciation": "/ˌɪmjʊnaɪˈzeɪʃən/",
                "meaning": "The process of making a person immune to a disease",
                "example": "Childhood immunization has greatly reduced the incidence of many diseases.",
                "difficulty": "medium",
            },
            {
                "word": "Pathology",
                "pronunciation": "/pəˈθɒlədʒi/",
                "meaning": "The science of the causes and effects of diseases",
                "example": "The pathology report confirmed that the tumor was benign.",
                "difficulty": "hard",
            },
            {
                "word": "Metabolism",
                "pronunciation": "/məˈtæbəlɪzəm/",
                "meaning": "The chemical processes that occur within a living organism to maintain life",
                "example": "A fast metabolism helps some people maintain their weight more easily.",
                "difficulty": "medium",
            },
            {
                "word": "Anesthesia",
                "pronunciation": "/ˌænəsˈθiːziə/",
                "meaning": "A state of controlled, temporary loss of sensation or awareness induced for medical purposes",
                "example": "The patient was put under general anesthesia before the surgery.",
                "difficulty": "medium",
            },
            {
                "word": "Epidemic",
                "pronunciation": "/ˌɛpɪˈdɛmɪk/",
                "meaning": "A widespread occurrence of an infectious disease in a community at a particular time",
                "example": "The flu epidemic affected thousands of people in the city.",
                "difficulty": "medium",
            },
            {
                "word": "Chronic",
                "pronunciation": "/ˈkrɒnɪk/",
                "meaning": "Persisting for a long time or constantly recurring",
                "example": "Diabetes is a chronic condition that requires ongoing management.",
                "difficulty": "medium",
            },
            {
                "word": "Remission",
                "pronunciation": "/rɪˈmɪʃən/",
                "meaning": "A temporary or permanent decrease or cessation of symptoms of a disease",
                "example": "The cancer has been in remission for five years.",
                "difficulty": "hard",
            },
            {
                "word": "Hypertension",
                "pronunciation": "/ˌhaɪpərˈtɛnʃən/",
                "meaning": "Abnormally high blood pressure",
                "example": "Lifestyle changes can help manage hypertension.",
                "difficulty": "medium",
            },
            {
                "word": "Oncology",
                "pronunciation": "/ɒnˈkɒlədʒi/",
                "meaning": "The study and treatment of tumors and cancer",
                "example": "She specializes in oncology at the university hospital.",
                "difficulty": "hard",
            },
            {
                "word": "Neurology",
                "pronunciation": "/nʊˈrɒlədʒi/",
                "meaning": "The branch of medicine dealing with the nervous system",
                "example": "The patient was referred to neurology for his recurring headaches.",
                "difficulty": "hard",
            },
            {
                "word": "Inflammation",
                "pronunciation": "/ˌɪnfləˈmeɪʃən/",
                "meaning": "A localized physical condition in which part of the body becomes reddened, swollen, hot, and often painful",
                "example": "Ice can help reduce inflammation after an injury.",
                "difficulty": "medium",
            },
            {
                "word": "Palliative",
                "pronunciation": "/ˈpæliətɪv/",
                "meaning": "Relieving pain without dealing with the cause of the condition",
                "example": "Palliative care focuses on improving quality of life for patients with serious illnesses.",
                "difficulty": "hard",
            },
            {
                "word": "Syndrome",
                "pronunciation": "/ˈsɪndroʊm/",
                "meaning": "A group of symptoms that consistently occur together",
                "example": "Down syndrome is caused by a chromosomal abnormality.",
                "difficulty": "medium",
            },
            {
                "word": "Holistic",
                "pronunciation": "/hoʊˈlɪstɪk/",
                "meaning": "Characterized by the treatment of the whole person, taking into account mental and social factors",
                "example": "The clinic takes a holistic approach to healthcare.",
                "difficulty": "medium",
            },
            {
                "word": "Pandemic",
                "pronunciation": "/pænˈdɛmɪk/",
                "meaning": "An epidemic of disease that has spread across a large region, multiple continents, or worldwide",
                "example": "COVID-19 was declared a global pandemic in March 2020.",
                "difficulty": "medium",
            },
            {
                "word": "Antihistamine",
                "pronunciation": "/ˌæntiˈhɪstəmiːn/",
                "meaning": "A drug that counteracts the effects of histamine in the body, used to treat allergies",
                "example": "She takes an antihistamine daily during pollen season.",
                "difficulty": "hard",
            },
        ],
        "Science & Nature": [
            {
                "word": "Photosynthesis",
                "pronunciation": "/ˌfoʊtoʊˈsɪnθəsɪs/",
                "meaning": "The process by which green plants use sunlight to synthesize foods from carbon dioxide and water",
                "example": "Through photosynthesis, plants convert light energy into chemical energy.",
                "difficulty": "hard",
            },
            {
                "word": "Ecosystem",
                "pronunciation": "/ˈiːkoʊˌsɪstəm/",
                "meaning": "A biological community of interacting organisms and their physical environment",
                "example": "Coral reefs are diverse ecosystems that support thousands of marine species.",
                "difficulty": "medium",
            },
            {
                "word": "Gravity",
                "pronunciation": "/ˈɡrævɪti/",
                "meaning": "The force that attracts a body toward the center of the earth or another physical body",
                "example": "Newton's law of gravity explains why objects fall to the ground.",
                "difficulty": "easy",
            },
            {
                "word": "Evolution",
                "pronunciation": "/ˌɛvəˈluːʃən/",
                "meaning": "The process by which different kinds of living organisms developed from earlier forms",
                "example": "Darwin's theory of evolution explains how species adapt to their environments over time.",
                "difficulty": "medium",
            },
            {
                "word": "Molecule",
                "pronunciation": "/ˈmɒlɪkjuːl/",
                "meaning": "A group of atoms bonded together, representing the smallest fundamental unit of a chemical compound",
                "example": "Water molecules consist of two hydrogen atoms and one oxygen atom.",
                "difficulty": "medium",
            },
            {
                "word": "Biodiversity",
                "pronunciation": "/ˌbaɪoʊdaɪˈvɜːrsɪti/",
                "meaning": "The variety of plant and animal life in a particular habitat",
                "example": "Rainforests have high biodiversity, containing countless species of plants and animals.",
                "difficulty": "hard",
            },
            {
                "word": "Hypothesis",
                "pronunciation": "/haɪˈpɒθəsɪs/",
                "meaning": "A proposed explanation for a phenomenon, made on the basis of limited evidence as a starting point for further investigation",
                "example": "The scientist developed a hypothesis about the cause of the disease.",
                "difficulty": "medium",
            },
            {
                "word": "Thermodynamics",
                "pronunciation": "/ˌθɜːrmoʊdaɪˈnæmɪks/",
                "meaning": "The branch of physics concerned with heat and temperature and their relation to energy and work",
                "example": "The laws of thermodynamics govern energy transfer and transformation.",
                "difficulty": "hard",
            },
            {
                "word": "Nucleus",
                "pronunciation": "/ˈnjuːkliəs/",
                "meaning": "The central and most important part of an object, movement, or group",
                "example": "The nucleus of an atom contains protons and neutrons.",
                "difficulty": "medium",
            },
            {
                "word": "Fossil",
                "pronunciation": "/ˈfɒsl/",
                "meaning": "The remains or impression of a prehistoric organism preserved in rock",
                "example": "The discovery of dinosaur fossils has helped scientists understand prehistoric life.",
                "difficulty": "easy",
            },
            {
                "word": "Quantum",
                "pronunciation": "/ˈkwɒntəm/",
                "meaning": "A discrete quantity of energy proportional in magnitude to the frequency of the radiation it represents",
                "example": "Quantum physics deals with the behavior of matter at the atomic and subatomic levels.",
                "difficulty": "hard",
            },
            {
                "word": "Symbiosis",
                "pronunciation": "/ˌsɪmbaɪˈoʊsɪs/",
                "meaning": "A close and long-term biological interaction between two different biological organisms",
                "example": "The relationship between clownfish and sea anemones is a classic example of symbiosis.",
                "difficulty": "hard",
            },
            {
                "word": "Catalyst",
                "pronunciation": "/ˈkætəlɪst/",
                "meaning": "A substance that increases the rate of a chemical reaction without itself undergoing any permanent chemical change",
                "example": "Enzymes act as catalysts in biological reactions.",
                "difficulty": "medium",
            },
            {
                "word": "Genetics",
                "pronunciation": "/dʒəˈnɛtɪks/",
                "meaning": "The study of heredity and the variation of inherited characteristics",
                "example": "Advances in genetics have led to breakthroughs in disease treatment.",
                "difficulty": "medium",
            },
            {
                "word": "Inertia",
                "pronunciation": "/ɪˈnɜːrʃə/",
                "meaning": "A property of matter by which it continues in its existing state of rest or uniform motion in a straight line, unless changed by an external force",
                "example": "Due to inertia, passengers in a car move forward when the driver brakes suddenly.",
                "difficulty": "medium",
            },
            {
                "word": "Adaptation",
                "pronunciation": "/ˌædæpˈteɪʃən/",
                "meaning": "The process of change by which an organism becomes better suited to its environment",
                "example": "The cactus's spines are an adaptation that helps it conserve water in the desert.",
                "difficulty": "medium",
            },
            {
                "word": "Mitosis",
                "pronunciation": "/maɪˈtoʊsɪs/",
                "meaning": "A type of cell division that results in two daughter cells each having the same number of chromosomes as the parent cell",
                "example": "Mitosis is essential for growth and repair in multicellular organisms.",
                "difficulty": "hard",
            },
            {
                "word": "Entropy",
                "pronunciation": "/ˈɛntrəpi/",
                "meaning": "A thermodynamic quantity representing the unavailability of a system's thermal energy for conversion into mechanical work",
                "example": "According to the second law of thermodynamics, the entropy of an isolated system always increases.",
                "difficulty": "hard",
            },
            {
                "word": "Tectonics",
                "pronunciation": "/tɛkˈtɒnɪks/",
                "meaning": "The study of the earth's structural features and their causes",
                "example": "Plate tectonics explains the movement of the Earth's lithosphere.",
                "difficulty": "hard",
            },
            {
                "word": "Osmosis",
                "pronunciation": "/ɒzˈmoʊsɪs/",
                "meaning": "The movement of a solvent through a semipermeable membrane from a less concentrated solution to a more concentrated one",
                "example": "Plant roots absorb water from the soil through osmosis.",
                "difficulty": "medium",
            },
        ],
        "Sports & Recreation": [
            {
                "word": "Endurance",
                "pronunciation": "/ɪnˈdʊərəns/",
                "meaning": "The ability to sustain prolonged physical or mental effort",
                "example": "Marathon runners need exceptional endurance to complete the race.",
                "difficulty": "medium",
            },
            {
                "word": "Agility",
                "pronunciation": "/əˈdʒɪlɪti/",
                "meaning": "The ability to move quickly and easily",
                "example": "Gymnasts demonstrate remarkable agility in their routines.",
                "difficulty": "medium",
            },
            {
                "word": "Technique",
                "pronunciation": "/tɛkˈniːk/",
                "meaning": "A skillful or efficient way of doing or achieving something",
                "example": "The swimmer improved her technique to increase her speed.",
                "difficulty": "medium",
            },
            {
                "word": "Stamina",
                "pronunciation": "/ˈstæmɪnə/",
                "meaning": "The ability to sustain prolonged physical or mental effort",
                "example": "Long-distance runners need excellent stamina.",
                "difficulty": "medium",
            },
            {
                "word": "Trajectory",
                "pronunciation": "/trəˈdʒɛktəri/",
                "meaning": "The path followed by a projectile flying or an object moving under the action of given forces",
                "example": "The golfer calculated the trajectory needed to avoid the sand trap.",
                "difficulty": "hard",
            },
            {
                "word": "Sportsmanship",
                "pronunciation": "/ˈspɔːrtsmənʃɪp/",
                "meaning": "Fair and generous behavior or treatment of others, especially in a sports contest",
                "example": "Good sportsmanship includes congratulating opponents after a game.",
                "difficulty": "medium",
            },
            {
                "word": "Aerobic",
                "pronunciation": "/ɛəˈroʊbɪk/",
                "meaning": "Relating to or denoting exercise that improves oxygen consumption by the body",
                "example": "Aerobic exercises like running and swimming improve cardiovascular fitness.",
                "difficulty": "medium",
            },
            {
                "word": "Anaerobic",
                "pronunciation": "/ˌænəˈroʊbɪk/",
                "meaning": "Relating to or denoting exercise that does not improve oxygen consumption by the body",
                "example": "Weightlifting is an anaerobic exercise that builds muscle strength.",
                "difficulty": "hard",
            },
            {
                "word": "Coordination",
                "pronunciation": "/koʊˌɔːrdɪˈneɪʃən/",
                "meaning": "The ability to use different parts of the body together smoothly and efficiently",
                "example": "Playing the piano requires good hand-eye coordination.",
                "difficulty": "medium",
            },
            {
                "word": "Regatta",
                "pronunciation": "/rɪˈɡætə/",
                "meaning": "A series of boat races",
                "example": "The annual regatta attracts rowing teams from around the world.",
                "difficulty": "hard",
            },
            {
                "word": "Triathlon",
                "pronunciation": "/traɪˈæθlən/",
                "meaning": "An athletic contest consisting of three different events, typically swimming, cycling, and running",
                "example": "She trained for months to compete in the Ironman triathlon.",
                "difficulty": "medium",
            },
            {
                "word": "Slalom",
                "pronunciation": "/ˈslɑːləm/",
                "meaning": "A skiing race down a winding course marked by poles or gates",
                "example": "The skier navigated the slalom course with impressive speed and precision.",
                "difficulty": "hard",
            },
            {
                "word": "Decathlon",
                "pronunciation": "/dɪˈkæθlɒn/",
                "meaning": "An athletic event in which each competitor takes part in ten events",
                "example": "The decathlon tests an athlete's all-around physical abilities.",
                "difficulty": "hard",
            },
            {
                "word": "Volley",
                "pronunciation": "/ˈvɒli/",
                "meaning": "A return of the ball before it touches the ground",
                "example": "The tennis player won the point with a powerful volley at the net.",
                "difficulty": "easy",
            },
            {
                "word": "Cadence",
                "pronunciation": "/ˈkeɪdəns/",
                "meaning": "The rhythm or flow of a sequence of movements or sounds",
                "example": "Cyclists maintain a steady cadence to maximize efficiency.",
                "difficulty": "medium",
            },
            {
                "word": "Dribble",
                "pronunciation": "/ˈdrɪbl/",
                "meaning": "To move a ball along by repeatedly tapping or bouncing it",
                "example": "The basketball player dribbled past the defenders to score.",
                "difficulty": "easy",
            },
            {
                "word": "Handicap",
                "pronunciation": "/ˈhændikæp/",
                "meaning": "A disadvantage imposed on a superior competitor to equalize chances of winning",
                "example": "In golf, a handicap system allows players of different abilities to compete fairly.",
                "difficulty": "medium",
            },
            {
                "word": "Traverse",
                "pronunciation": "/trəˈvɜːrs/",
                "meaning": "To move across or through",
                "example": "The climbers had to traverse a narrow ledge to reach the summit.",
                "difficulty": "hard",
            },
            {
                "word": "Orienteering",
                "pronunciation": "/ˌɔːriənˈtɪərɪŋ/",
                "meaning": "A competitive sport in which participants find their way to various checkpoints with the aid of a map and compass",
                "example": "Orienteering requires both physical stamina and navigational skills.",
                "difficulty": "hard",
            },
            {
                "word": "Camaraderie",
                "pronunciation": "/ˌkæməˈrɑːdəri/",
                "meaning": "Mutual trust and friendship among people who spend a lot of time together",
                "example": "Team sports foster camaraderie among players.",
                "difficulty": "hard",
            },
        ],
        "Education & Academia": [
            {
                "word": "Pedagogy",
                "pronunciation": "/ˈpɛdəɡɒdʒi/",
                "meaning": "The method and practice of teaching",
                "example": "The school adopted a new pedagogy that emphasizes hands-on learning.",
                "difficulty": "hard",
            },
            {
                "word": "Curriculum",
                "pronunciation": "/kəˈrɪkjʊləm/",
                "meaning": "The subjects comprising a course of study in a school or college",
                "example": "The curriculum includes mathematics, science, and language arts.",
                "difficulty": "medium",
            },
            {
                "word": "Dissertation",
                "pronunciation": "/ˌdɪsərˈteɪʃən/",
                "meaning": "A long essay on a particular subject, especially one written for a university degree",
                "example": "She spent a year researching and writing her doctoral dissertation.",
                "difficulty": "hard",
            },
            {
                "word": "Academia",
                "pronunciation": "/ˌækəˈdiːmiə/",
                "meaning": "The environment or community concerned with the pursuit of research, education, and scholarship",
                "example": "After graduation, she pursued a career in academia as a professor.",
                "difficulty": "medium",
            },
            {
                "word": "Syllabus",
                "pronunciation": "/ˈsɪləbəs/",
                "meaning": "An outline of the subjects in a course of study",
                "example": "The professor distributed the syllabus on the first day of class.",
                "difficulty": "medium",
            },
            {
                "word": "Plagiarism",
                "pronunciation": "/ˈpleɪdʒərɪzəm/",
                "meaning": "The practice of taking someone else's work or ideas and passing them off as one's own",
                "example": "The university has strict policies against plagiarism.",
                "difficulty": "medium",
            },
            {
                "word": "Tenure",
                "pronunciation": "/ˈtɛnjər/",
                "meaning": "The holding of an academic position on a permanent basis",
                "example": "After six years of teaching and research, she was granted tenure.",
                "difficulty": "medium",
            },
            {
                "word": "Colloquium",
                "pronunciation": "/kəˈloʊkwiəm/",
                "meaning": "An academic conference or seminar",
                "example": "The department hosts a weekly colloquium where faculty present their research.",
                "difficulty": "hard",
            },
            {
                "word": "Didactic",
                "pronunciation": "/daɪˈdæktɪk/",
                "meaning": "Intended to teach, particularly in having moral instruction as an ulterior motive",
                "example": "The novel has a didactic tone, clearly trying to impart life lessons to the reader.",
                "difficulty": "hard",
            },
            {
                "word": "Empirical",
                "pronunciation": "/ɛmˈpɪrɪkəl/",
                "meaning": "Based on, concerned with, or verifiable by observation or experience rather than theory or pure logic",
                "example": "The scientist collected empirical data through careful experiments.",
                "difficulty": "hard",
            },
            {
                "word": "Erudite",
                "pronunciation": "/ˈɛrʊdaɪt/",
                "meaning": "Having or showing great knowledge or learning",
                "example": "The professor was known for his erudite lectures on ancient philosophy.",
                "difficulty": "hard",
            },
            {
                "word": "Seminar",
                "pronunciation": "/ˈsɛmɪnɑːr/",
                "meaning": "(In a university) a class at which a topic is discussed by a teacher and a small group of students",
                "example": "The graduate seminar focused on contemporary literary theory.",
                "difficulty": "medium",
            },
            {
                "word": "Thesis",
                "pronunciation": "/ˈθiːsɪs/",
                "meaning": "A statement or theory that is put forward as a premise to be maintained or proved",
                "example": "Her thesis argued that social media has fundamentally changed human communication.",
                "difficulty": "medium",
            },
            {
                "word": "Methodology",
                "pronunciation": "/ˌmɛθəˈdɒlədʒi/",
                "meaning": "A system of methods used in a particular area of study or activity",
                "example": "The research methodology included both quantitative and qualitative approaches.",
                "difficulty": "hard",
            },
            {
                "word": "Prerequisite",
                "pronunciation": "/priˈrɛkwəzɪt/",
                "meaning": "A thing that is required as a prior condition for something else to happen or exist",
                "example": "Calculus is a prerequisite for advanced physics courses.",
                "difficulty": "medium",
            },
            {
                "word": "Sabbatical",
                "pronunciation": "/səˈbætɪkəl/",
                "meaning": "A period of paid leave granted to a university teacher for study or travel",
                "example": "The professor took a sabbatical to conduct research in Europe.",
                "difficulty": "medium",
            },
            {
                "word": "Interdisciplinary",
                "pronunciation": "/ˌɪntərdɪsəˈplɪnəri/",
                "meaning": "Relating to more than one branch of knowledge",
                "example": "The interdisciplinary program combines elements of biology, chemistry, and physics.",
                "difficulty": "hard",
            },
            {
                "word": "Accreditation",
                "pronunciation": "/əˌkrɛdɪˈteɪʃən/",
                "meaning": "The action of officially recognizing someone as having a particular status or being qualified to perform a particular activity",
                "example": "The university received accreditation from the national education board.",
                "difficulty": "medium",
            },
            {
                "word": "Matriculation",
                "pronunciation": "/məˌtrɪkjʊˈleɪʃən/",
                "meaning": "The process of enrolling at a college or university",
                "example": "Matriculation ceremonies welcome new students to the university.",
                "difficulty": "hard",
            },
            {
                "word": "Cognition",
                "pronunciation": "/kɒɡˈnɪʃən/",
                "meaning": "The mental action or process of acquiring knowledge and understanding through thought, experience, and the senses",
                "example": "The study examined how aging affects cognition and memory.",
                "difficulty": "hard",
            },
        ],
    }

    # Create vocabulary for each topic
    for topic in created_topics:
        if topic.name in vocabulary_data:
            vocab_list = vocabulary_data[topic.name]
            for vocab_data in vocab_list:
                vocabulary, created = Vocabulary.objects.get_or_create(
                    word=vocab_data["word"],
                    topic=topic,
                    defaults={
                        "pronunciation": vocab_data["pronunciation"],
                        "meaning": vocab_data["meaning"],
                        "example": vocab_data["example"],
                        "difficulty": vocab_data["difficulty"],
                    },
                )
                if created:
                    print(
                        f"  ✓ Vocabulary '{vocabulary.word}' created for topic '{topic.name}'"
                    )
if __name__ == "__main__":
    create_sample_data()
