# Generated by Django 5.2.2 on 2025-06-07 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='not_started', max_length=15)),
                ('correct_count', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('last_studied', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabulary.vocabulary')),
            ],
            options={
                'ordering': ['-last_studied'],
                'unique_together': {('user', 'vocabulary')},
            },
        ),
    ]
